workflows:
  ios-method-1:
    name: iOS Signing Method-1 Workflow
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mycompany.romanita
    scripts:
      - script: keychain initialize
      - script: keychain add-certificates
      - script: xcode-project use-profiles
      - script: flutter packages pub get
      - name: Flutter Build IPA and Automatic Versioning
        script: flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - info@romanytas.com

  ios-method-2:
    name: iOS Signing Method-2 Workflow
    environment:
      ios_signing:
        provisioning_profiles: 
          - ProvProfile_Romanytas
        certificates:
          - Distribute_certificate
    scripts:
      - script: keychain initialize
      - script: keychain add-certificates
      - script: xcode-project use-profiles
      - script: flutter packages pub get
      - name: Flutter Build IPA and Automatic Versioning
        script: flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - info@romanytas.com
