name: romanytas
description: A new Flutter project.

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Application version and build number
version: 4.0.8+408

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core dependencies
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  cloud_firestore: 4.17.3
  cloud_functions: 4.7.4
  collection: 1.18.0
  easy_debounce: 2.0.1
  equatable: 2.0.5
  file_picker: 8.0.3
  firebase_analytics: 10.10.5
  firebase_auth: 4.19.5
  firebase_core: 2.31.0
  firebase_dynamic_links: 5.4.16
  firebase_messaging: 14.9.2
  firebase_performance: 0.9.4+5
  firebase_storage: 11.7.5

  # UI and animations
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.3.1
  flutter_google_places: 
    git:
      url: https://github.com/ShehanYjoz/flutter_google_places.git
  flutter_keyboard_visibility: 5.4.1
  flutter_native_splash: 2.3.1
  font_awesome_flutter: 10.6.0

  # Google services
  go_router: 12.1.3
  google_fonts: 6.1.0
  google_maps: 7.1.0
  google_maps_flutter: 2.6.1
  google_mobile_ads: 5.1.0
  google_sign_in: 6.1.5
  
  # Miscellaneous
  geolocator: 12.0.0
  http: 1.2.1
  image_picker: 1.0.4
  intl: 0.19.0
  json_path: 0.7.2
  mapbox_search: 4.2.2
  mime_type: 1.0.0
  package_info_plus: 8.0.0
  page_transition: 2.1.0
  path_provider: 2.1.3
  permission_handler: ^11.1.0
  plugin_platform_interface: 2.1.8
  pointer_interceptor: 0.10.1
  provider: 6.1.2
  rxdart: 0.27.7
  share_plus: 9.0.0
  shared_preferences: 2.2.2
  sign_in_with_apple: 4.3.0
  smooth_page_indicator: 1.1.0
  sqflite: 2.2.6
  timeago: 3.6.1
  universal_io: 2.2.2
  url_launcher: 6.3.0
  video_player: 2.8.6
  xml: 6.5.0

  #Extras
  stream_transform: 2.1.0
  from_css_color: 2.0.0
  flutter_plugin_android_lifecycle: 2.0.20
  in_app_review: ^2.0.6
  facebook_audience_network: ^1.0.1
  facebook_app_events: ^0.19.3

  # Cupertino icons for iOS style icons
  cupertino_icons: ^1.0.0

# Dependency overrides
dependency_overrides:
  http: 1.2.1
  package_info_plus: 8.0.0
  pointer_interceptor: ^0.10.1+1
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  image: 4.0.17
  integration_test:
    sdk: flutter
  lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'
  adaptive_icon_background: 'assets/images/adaptive_background_icon.png'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/sqlite_db_files/

  fonts:
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
